### ISSUE TITLE
Feature Request: Site Shell

### ISSUE THREAD

**Issue by allen-mckenzie** [getflywheel/local-cli#11]
I would love to see the option to jump into a site shell from the terminal which you can do already once you have opened a shell from the app dashboard and run the generated shell script that local creates for that site.

Example:
| ID | Name | Status |
|---|-------|--------|
| 2DYPBV1dU | sandbox | started |

`local-cli shell 2DYPBV1dU` would effectively be launching the shell script found in `.../Local/ssh-entry/2DYPBV1dU.sh` using the same hash ID you would use to start and stop the site.

This would allow me to remain within the terminal, start a local site, jump into that site shell, perform actions using wp-cli, and then exit the shell, and stop a site without ever having to touch the app itself. This could be made further useful with some automation scripts to help folks who use local in their daily work to test various projects locally before pushing changes to other repositories or out to staging sites.

**Comment by ethanclevenger91** [comment]
See #5

**Comment by allen-mckenzie** [comment]
The issues raised in #5 are duplicated by this request and #5 should be where this effort is tracked :) Looking forward to see this become a feature!!
